import { createClient } from "@/utils/supabase/server";
import { NextResponse } from "next/server";

export async function GET(request: Request) {
    const requestUrl = new URL(request.url);
    const { searchParams } = requestUrl;
    const code = searchParams.get("code");
    const next = searchParams.get("next") ?? "/dashboard";
    const origin = requestUrl.origin;

    // Simplification: We trust the link generated by actions.ts is correct.
    // We only ensure the FINAL destination uses the canonical URL to set cookies correctly.
    let finalRedirectOrigin = process.env.NEXT_PUBLIC_SITE_URL || process.env.NEXTAUTH_URL || origin;

    // Normalize final origin
    if (finalRedirectOrigin && finalRedirectOrigin.endsWith('/')) {
        finalRedirectOrigin = finalRedirectOrigin.slice(0, -1);
    }
    if (finalRedirectOrigin && !finalRedirectOrigin.startsWith('http')) {
        finalRedirectOrigin = `https://${finalRedirectOrigin}`;
    }

    if (code) {
        const supabase = await createClient();
        const { error } = await supabase.auth.exchangeCodeForSession(code);

        if (!error) {
            // Redirect to the intended page on the canonical domain
            return NextResponse.redirect(`${finalRedirectOrigin}${next}`);
        }

        console.error("Auth Callback Error:", error);
        return NextResponse.redirect(`${finalRedirectOrigin}/login?error=${encodeURIComponent(error.message)}`);
    }

    return NextResponse.redirect(`${finalRedirectOrigin}/login?error=Could not authenticate user`);
}
